### ISSUE TITLE
Houdini: Combination of two extensions for loaders in pointcache product type 

### ISSUE THREAD

**Issue by moonyuet** [ynput/ayon-houdini#11]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

In Houdini, we are publishing the pointcache in either bgeo or abc format. We have two loaders(bgeo and abc) to load the cache in different formats respectively. These cause the issues of updating or switching assets if we dont have both `bgeo` or `abc` format published. The issues also block publishing assets with the asset, which is not at the latest version, where the validator (Validate Outdated Container) would check on the outdated container to ensure the version is at the latest.

### Expected Behavior:

We expect to have just one loader plugin for pointcache product type which loads bgeo or abc format for the scene inventory tools to be concise on which format they are going to update/switch in pointcache product type

### Version

1.0.0

### What platform you are running on?

Windows

### Steps To Reproduce:

1. Publish pointcache(bgeo) wihout pointcache(abc)
2. Publish pointcache(abc) without pointcache(bgeo)
3. Have a new scene
4. Load the pointache product type
5. Go to Manage
6. Update or Change Versions of the assets
7. You will get the error below
```
Traceback (most recent call last):
  File "D:\ayon-core\client\ayon_core\tools\sceneinventory\view.py", line 250, in <lambda>
    lambda: self._update_containers(items, version=-1)
  File "D:\ayon-core\client\ayon_core\tools\sceneinventory\view.py", line 822, in _update_containers
    update_container(item, item_version)
  File "D:\ayon-core\client\ayon_core\pipeline\load\utils.py", line 508, in update_container
    repre_name
ValueError: Representation 'abc' wasn't found on requested version
```
or 
```
Traceback (most recent call last):
  File "D:\ayon-core\client\ayon_core\tools\sceneinventory\view.py", line 250, in <lambda>
    lambda: self._update_containers(items, version=-1)
  File "D:\ayon-core\client\ayon_core\tools\sceneinventory\view.py", line 822, in _update_containers
    update_container(item, item_version)
  File "D:\ayon-core\client\ayon_core\pipeline\load\utils.py", line 508, in update_container
    repre_name
ValueError: Representation 'bgeo' wasn't found on requested version
```

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

[cuID:[AY-4794](https://app.clickup.com/t/86by88z95)]

**Comment by BigRoy** [comment]
Not sure what we'd want to do here - it regards two issues in one: publishing and loading. I think there is little that we can do without making either a dedicated HDA that loads either - or find other ways to use it.

### Loading

For Loaders, technically we could implement "switch" logic that would actually recreate the node of the switched to loader if it's of a different type, etc. But so far there hasn't been much noise or interest about requiring that.

### Publishing

Yes, this is tricky - especially because this is just how Houdini works, it has different nodes for different outputs. The only thing we could embrace is potentially the #122 PR which allows to publish input ROPs, including support for publishing multiple representations into one product. It's likely our best bet moving forward.

**Comment by MustafaJafar** [comment]
I gave it a thought and let me share the first idea on top of my head. 

### Use HDAs

Other addons have python API to load and publish different formats. and switching between these APIs/flags is done on the code level in loader and publish plugins. 

However, in Houdini we have nodes instead of python APIs to perform these actions. So Houdini may go anti that pattern and have that switching happening outside of the code. i.e. by a switch node.

I think this is true for publishing and loading.

#### Loading

I think because we have generic loaders with representation filter. it can make this easier to implement in  a similar manner to LOP loaders.

![Image](https://github.com/user-attachments/assets/a0207770-a58c-484d-838e-4f26c28f1874)

But a new question will arise do we want to build an HDA loader for each product or do we want it to be generic (with a big switch inside).

#### Creators

IMO, it's a lot similar to Multiple Representations Support issue. which can grow to be a different topic.

### Multiple Representations Support
Also, to add one more layer of complexity: 
What if some user wants to publish the same pointcache product with multiple representations: `bgeo` and `abc` ?

At the moment there are two ideas on the table: 
- Generic Instance: #2
- AYON Publish ROP: #122

| Generic | AYON Publish Rop |
|--|--|
| <img  width="800" src=https://github.com/user-attachments/assets/20cf7317-8abd-49c0-bd98-fc7d20af8fd8> | <img  width="600" src=https://github.com/user-attachments/assets/16a46752-0d9b-4ce1-95c6-a163338a0bb4> |
