### ISSUE TITLE
`read` function should only get AYON parameters

### ISSUE THREAD

**Issue by MustafaJafar** [ynput/ayon-houdini#173]
### Is there an existing issue for this?

- [x] I have searched the existing issues and added correct labels.

## Current Behavior
[ayon_houdini.api.lib.read](https://github.com/ynput/ayon-houdini/blob/45b780634b5ca4ab5ac8cdb55280c2325117b8a1/client/ayon_houdini/api/plugin.py#L180) should get extra AYON parameters.

Houdini Nodes can include different type of parameters and some of them like `ramp` breaks the instances collection as copy.deepcopy fails.
Here's some bug report when it fails
<details><summary>cannot pickle 'SwigPyObject' object</summary>

```python
Traceback (most recent call last):
  File "E:\Ynput\ayon-core\client\ayon_core\pipeline\create\context.py", line 1395, in reset_instances
    creator.collect_instances()
  File "E:\Ynput\ayon-houdini\client\ayon_houdini\api\plugin.py", line 193, in collect_instances
    node_data, self
                   
  File "E:\Ynput\ayon-core\client\ayon_core\pipeline\create\structures.py", line 800, in from_existing
    instance_data = copy.deepcopy(instance_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.370\python311\Lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.370\python311\Lib\copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.370\python311\Lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.370\python311\Lib\copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
            ^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.370\python311\Lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.370\python311\Lib\copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.370\python311\Lib\copy.py", line 161, in deepcopy
    rv = reductor(4)
         ^^^^^^^^^^^
TypeError: cannot pickle 'SwigPyObject' object
```
</details>

when checking the instance data, it shown something like 
```python
'color_ramp': <hou.Ramp is_color=True num_keys=2 data=((t=0, rgb=(0, 0, 0)), (t=1, rgb=(1, 1, 1)))>,
```

## Expected Behavior
`read` function should only get AYON parameters

### Steps To Reproduce:

1. Create an HDA product
2. Add a ramp parameter
3. open the publisher tool or click refresh button,

### Version
latest everything

### What platform were you running when you found the bug?
Windows

You can also provide any additional information relevant to the issue.

### Relevant log output:

```shell

```

**Comment by BigRoy** [comment]
Yes - for the containers we already did this, but we should also for creators. (It may also make them faster!) 

So we would be getting way more explicit about the attributes we're expecting. However, currently those are quite a lot already - especially with backwards compatibility:

```python
# creators
keys = [
    "folderPath", 
    "task", 
    "creator_identifier", 
    "id", 
    "AYON_productName", 
    "productName", 
    "creator_attributes", 
    "publish_attributes",
    "variant",
    "active",
    # legacy attributes
    "asset", 
    "subset"
]
```
And I might still be missing some?
