### ISSUE TITLE
HDA creation fails when project name starts with number

### ISSUE THREAD

**Issue by MustafaJafar** [ynput/ayon-houdini#52]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

HDA creation fails when project name starts with number.
Houdini doesn't names that start with number.  
and, we currently use this hardcoded template name `{project_name}{folder_path}_{node_name}` for HDA asset type.
Which result in this line in Houdini's log
```
The name must start with an alphabetic character.
```
however it works fine for projects starts with an alphabetic character. here's an example from my end.

### Expected Behavior:

We should find some solution for it.

### Version

1.0.0

### What platform you are running on?

Windows

### Steps To Reproduce:

1. Launch Houdini in an AYON project starts with a number.
2. Create an HDA

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

### Relevant log output:

```shell
Traceback (most recent call last):
  File "E:\Ynput\ayon-houdini\client\ayon_houdini\api\plugin.py", line 125, in create
    instance_node = self.create_instance_node(
  File "E:\Ynput\ayon-houdini\client\ayon_houdini\plugins\create\create_hda.py", line 221, in create_instance_node
    hda_node = to_hda.createDigitalAsset(
  File "C:\PROGRA~1/SIDEEF~1/HOUDIN~1.805/houdini/python3.9libs\houpythonportion\ui.py", line 1119, in decorator
    return func(*args, **kwargs)
  File "C:\PROGRA~1/SIDEEF~1/HOUDIN~1.805/houdini/python3.9libs\hou.py", line 16238, in createDigitalAsset
    return _hou.Node_createDigitalAsset(self, name, hda_file_name, description, min_num_inputs, max_num_inputs, compress_contents, comment, version, save_as_embedded, ignore_external_references, compile_asset, change_node_type, create_backup, install_path)
hou.OperationFailed: The attempted operation failed.
The name must start with an alphabetic character.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ayon_create.io.openpype.creators.houdini.hda", line 3, in <module>
  File "E:\Ynput\ayon-houdini\client\ayon_houdini\api\creator_node_shelves.py", line 119, in create_interactive
    context.create(
  File "E:\Ynput\ayon-core\client\ayon_core\pipeline\create\context.py", line 2140, in create
    return creator.create(
  File "E:\Ynput\ayon-houdini\client\ayon_houdini\api\plugin.py", line 152, in create
    six.reraise(
  File "E:\Ynput\ayon-launcher\.venv\lib\site-packages\six.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "E:\Ynput\ayon-houdini\client\ayon_houdini\api\plugin.py", line 125, in create
    instance_node = self.create_instance_node(
  File "E:\Ynput\ayon-houdini\client\ayon_houdini\plugins\create\create_hda.py", line 221, in create_instance_node
    hda_node = to_hda.createDigitalAsset(
  File "C:\PROGRA~1/SIDEEF~1/HOUDIN~1.805/houdini/python3.9libs\houpythonportion\ui.py", line 1119, in decorator
    return func(*args, **kwargs)
  File "C:\PROGRA~1/SIDEEF~1/HOUDIN~1.805/houdini/python3.9libs\hou.py", line 16238, in createDigitalAsset
    return _hou.Node_createDigitalAsset(self, name, hda_file_name, description, min_num_inputs, max_num_inputs, compress_contents, comment, version, save_as_embedded, ignore_external_references, compile_asset, change_node_type, create_backup, install_path)
ayon_core.pipeline.create.creator_plugins.CreatorError: Creator error: The attempted operation failed.
The name must start with an alphabetic character.
```

### Additional context:

Sometimes we can't avoid starting project names with numbers.

**Comment by MustafaJafar** [comment]
@moonyuet @BigRoy 
What do you think guys about this issue ? 
I thought about exposing the HDA asset type in HDA creator settings, which may/might break something or bring this issue back https://github.com/ynput/ayon-core/issues/534 .

**Comment by BigRoy** [comment]
I'm not sure - we may need to discuss this in a call. I still wonder why this is "so complicated" even though we have full control over how we name the HDA inside the file.

As far as I know the filename containing the HDA can have any name, including starting with a number whilst the node it defines internally we can define any name we want as well. I wonder what is currently REALLY restricting that "alphabetic number" thing, etc.

**Comment by MustafaJafar** [comment]
it's the `to_hda.createDigitalAsset`  call. it didn't like the `type_name` that starts with number.

**Comment by MustafaJafar** [comment]
> This is really weird bug and it's only happened when you have a scene starting with a number?


The problem happens because the project name is put at the beginning of the HDA type name template which causes Houdini to error as the asset type name in this situation will be starting by a number.

https://github.com/ynput/ayon-houdini/blob/649c6115b40faf6302fb2e5850d9f1a59a823a62/client/ayon_houdini/plugins/create/create_hda.py#L212-L226

**Comment by BigRoy** [comment]
What we've done in the past when e.g. defining namespaces for maya using the folder name when a folder name started with digits (which maya doesn't like in node names or namespaces) then we prefixed it with `_`. I wonder if that'd be 'ok' here too?

Or does that make usage of the node that much less nice?
Or we just always prefix it with `AYON_` hehe. Or `hda_` - also doesn't sound too nice.

**Comment by MustafaJafar** [comment]
> What we've done in the past when e.g. defining namespaces for maya using the folder name when a folder name started with digits (which maya doesn't like in node names or namespaces) then we prefixed it with `_`. I wonder if that'd be 'ok' here too?

I wonder if we should expose that template name to settings with a note about changing the name may break something ?

> Or does that make usage of the node that much less nice? Or we just always prefix it with `AYON_` hehe. Or `hda_` - also doesn't sound too nice.

"hda_{project_name}{folder_path}_{node_name}" 🤔 this could work.

**Comment by BigRoy** [comment]
When does the user 'access' these names? Where does it see it? what does it influence? The default node name when created? In the tab creation menu?


Also, _what if_ we just start the type name with the node name (but end with the project and folder path?)

**Comment by MustafaJafar** [comment]
It doesn't affect the node name at all.
It won't show up to users until they enable viewing asset definition. 
where they will be able to see the type name. 
![image](https://github.com/user-attachments/assets/2f0e6677-5cf9-4d95-8843-73ec522bcea3)

I think reversing the template will fix the problem as well.
`{node_name}_{project_name}{folder_path}`

**Comment by BigRoy** [comment]
> I think reversing the template will fix the problem as well.
> {node_name}_{project_name}{folder_path}

Maybe that is nicer anyway so that the node name (defining the type's name) is the most visible? :)

**Comment by MustafaJafar** [comment]
> Maybe that is nicer anyway so that the node name (defining the type's name) is the most visible? :)

Maybe. also, it is defiantly starts with a alphabetic character.

**Comment by BigRoy** [comment]
Maybe confirm with client whether it's "fine" for them as well, and when confirmed - make a PR to swap it around to resolve the issue for now. We can always keep an issue open to investigate other ways to customize it? Or maybe the user can already customize it manually after create?
