### ISSUE TITLE
Update USD outputprocessor API to support 20.5+

### ISSUE THREAD

**Issue by BigRoy** [ynput/ayon-houdini#53]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

It seems that Houdini decided to change the USD output processors' API between houdini 20.0.724 and houdini 20.5.278 where `beginSave()` method takes a different signature and amount of arguments, resulting in:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: AYONRemapPaths.beginSave() takes 5 positional arguments but 6 were given
```

According to the docs [here](https://www.sidefx.com/docs/houdini/solaris/output.html) it seemed to start taking a new argument `stage_variables` as last argument.

Changing this:
```
    def beginSave(self, config_node, config_overrides, lop_node, t):
```
To this:
```
    def beginSave(self, config_node, config_overrides, lop_node, t, stage_variables):
```

### Expected Behavior:

We will need to look into the easiest way to have the method allow it to be called both ways.

### Version

1.0.0

### What platform you are running on?

Windows

### Steps To Reproduce:

1. Run Houdini 20.5+
2. Publish a USD file with USD contributions enabled.
3. Error appears

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

### Relevant log output:

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: AYONRemapPaths.beginSave() takes 5 positional arguments but 6 were given
```

**Comment by BigRoy** [comment]
For context - these are the notable changelogs:
![image](https://github.com/user-attachments/assets/c695d8ba-5f16-4ed7-947c-87a5f6074a4a)

[Search `beginSave` on SideFX changelog](https://www.sidefx.com/changelog/?journal=&categories=&body=beginSave&version=&build_min=&build_max=&show_versions=on&show_compatibility=on&items_per_page=)
