### ISSUE TITLE
UNC paths don't work on Houdini template paths

### ISSUE THREAD

**Issue by MustafaJafar** [ynput/ayon-houdini#66]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

This line is the responsible for this weird behavior https://github.com/ynput/ayon-houdini/blob/c239540d12742b61893fb2bbf4042d434e616b9d/client/ayon_houdini/api/workfile_template_builder.py#L108
Where it trims all the slashes (except one) at the beginning of the path.

Will looking for alternatives.

### Expected Behavior:

UNC paths should work

### Version

1.0.0

### What platform you are running on?

Windows

### Steps To Reproduce:

1. Set your houdini template path to a UNC path
2. Build workflie from template 
3. Houdini should complain, it can't find the template path.

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

### Relevant log output:

```shell
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "E:\Ynput\ayon-houdini\client\ayon_houdini\api\workfile_template_builder.py", line 245, in build_workfile_template
    builder.build_template()
  File "E:\Ynput\ayon-core\client\ayon_core\pipeline\workfile\workfile_template_builder.py", line 523, in build_template
    template_preset = self.get_template_preset()
  File "E:\Ynput\ayon-houdini\client\ayon_houdini\api\workfile_template_builder.py", line 135, in get_template_preset
    raise TemplateNotFound(
ayon_core.pipeline.workfile.workfile_template_builder.TemplateNotFound: Template found in AYON settings for task 'cfx' with host 'houdini' does not exists. (Not found : \storage\studio\templates\my_houdini_template.hip)
```

**Comment by MustafaJafar** [comment]
Currently, there's a work around. This works on my side.
1. Added a new Houdini Var.
2. Used it in the template profile path
 
![image](https://github.com/user-attachments/assets/f4e33579-ffe4-47e3-9396-b3a1f5ac0f6b)
